### PR TITLE
Fix all of the e2e tests

### PR DESCRIPTION
**Pull request by benpsnyder**
This is a WIP. I am making the PR early to collaboratively track progress.

### CODE REVIEW

**Comment by benpsnyder** [comment]
@srleecode check out https://github.com/nrwl/nx/issues/7504 👯

**Comment by srleecode** [comment]
After installing with yarn, I get the below error when running yarn affected:e2e --all. I don't get this error when installing with npm. I also get a similar error using mac "spawnSync /bin/sh ENOENT". I get this with the normal yarn version as well as after running "yarn set version berry" then "yarn set version 3.x" and installing with yarn

spawnSync C:\Windows\System32\cmd.exe ENOENT
      at runNxNewCommand (../../../../packages/nx-plugin/src/utils/testing-utils/nx-project.ts:15:18)
      at Object.newNxProject (../../../../packages/nx-plugin/src/utils/testing-utils/nx-project.ts:72:3)

**Comment by benpsnyder** [comment]
@srleecode off... I ran successfully with:
````
yarn run e2e:domain-cypress-domain-test
yarn run e2e:domain-front-end-angular
yarn run e2e:domain-grouping-folder
yarn run e2e:domain-mock-file
````

**Comment by benpsnyder** [comment]
I see the issue.... no `--packageManager=yarn` is set
image

This must be specific to the `affected` command. I will need to update the patches I think. Hang tight.

**Pull request merged**
